apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

commonLabels:
  app.kubernetes.io/name: openebs
  app.kubernetes.io/component: system

resources:
- namespace.yaml
- openebs-operator.yaml

