defaultStorageConfig:
  enabled: "false"

apiserver:
  image: "openebs/m-apiserver-arm64"

provisioner:
  image: "openebs/openebs-k8s-provisioner-arm64"

localprovisioner:
  image: "openebs/provisioner-localpv-arm64"

snapshotOperator:
  controller:
    image: "openebs/snapshot-controller-arm64"
  provisioner:
    image: "openebs/snapshot-provisioner-arm64"

ndm:
  image: "openebs/node-disk-manager"
  filters:
    includePaths: "/dev/sda"

ndmOperator:
  image: "openebs/node-disk-operator"

webhook:
  image: "openebs/admission-server-arm64"

jiva:
  image: "openebs/jiva-arm64"

cstor:
  pool:
    image: "openebs/cstor-pool-arm64"
  poolMgmt:
    image: "openebs/cstor-pool-mgmt-arm64"
  target:
    image: "openebs/cstor-istgt-arm64"
  volumeMgmt:
    image: "openebs/cstor-volume-mgmt-arm64"

helper:
  image: "openebs/linux-utils-arm64"

policies:
  monitoring:
    image: "openebs/m-exporter-arm64"
