apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3os-system
resources:
- plan.yaml

commonLabels:
  app: kernel-modules

secretGenerator:
- name: kernel-modules
  files:
  - partials/modules.yaml
  - partials/execute.sh

generatorOptions:
  disableNameSuffixHash: true
