# Choose an optional name for the datacenter
global:
  datacenter: k8s_nazarewk_pw

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'ClusterIP'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true

client:
  enabled: true

# Use only one Consul server for local development
server:
  replicas: 3
  bootstrapExpect: 3
  storage: 2Gi
