apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  version: 0.5.0

  valuesContent: |-
    global:
      tlsDisable: false

    server:
      image:
        tag: 1.4.2

      ha:
        enabled: true
        raft:
          enabled: true

      readinessProbe:
        enabled: true

      ingress:
        enabled: true

        annotations:
          'external-dns.alpha.kubernetes.io/target': 'nazarewk.pw'

        hosts:
        - host: vault.nazarewk.pw

    injector:
      revokeOnShutdown: true
      image:
        repository: nazarewk/vault-k8s-arm64
        tag: "v0.3.0"
        pullPolicy: Always
