apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

commonLabels:
  app: metallb

resources:
- namespace.yaml
- metallb.yaml
- configmap.yaml

secretGenerator:
- name: memberlist
  files:
  - partials/secretkey

generatorOptions:
 disableNameSuffixHash: true
