apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns
resources:
- rbac.yaml
- deployment.yaml
- namespace.yaml

commonLabels:
  app: external-dns

secretGenerator:
- name: cloudflare-credentials
  files:
  - partials/CF_API_EMAIL
  - partials/CF_API_KEY
  - partials/DOMAIN
